GET  http://localhost:5000/form/0c901ff8-068a-4a0d-9dd3-0f20a06464d3/data HTTP/1.1
content-type: application/json

{
    "name": "test form 7",
    "options":{"fullname":true,"phone":true,"mail":true}
}